name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.runner.os }}
    strategy:
      fail-fast: false

      matrix:
        runner:
          # Current stable version
          - version: '1'
            os: ubuntu-latest
          # Minimum supported version
          - version: 'min'
            os: ubuntu-latest
          # Windows
          - version: '1'
            os: windows-latest
          # macOS
          - version: '1'
            os: macos-latest

    steps:
      - uses: actions/checkout@v5

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.runner.version }}

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: Tests

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
